<?php
/**
 * User: surprisepeas
 * Date: 2017/9/21 21:59
 */

namespace backend\controllers;


use backend\components\event\MailEvent;
use yii\web\Controller;
use Yii;

class EventController extends Controller
{
    const EVENT_TEST = 'event_test';
    const HELLO_TEST = 'hello_test';
    const SEND_MAIL = 'send_mail';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::HELLO_TEST, function () {
            echo 'Hello--';
        });
        $this->on(self::EVENT_TEST, function () {
            echo 'event test';
        });
        $this->on(self::SEND_MAIL, ['backend\components\Mail', 'sendMail']);
    }

    public function actionIndex(int $id)
    {
        if ($id === 1) {
            $this->trigger(self::EVENT_TEST);
        } else {
            $this->trigger(self::HELLO_TEST);
        }
    }


    public function actionSendMail()
    {
        $event = new MailEvent();
        $event->email = '1027132125@qq.com';
        $event->subject = 'Hi Man';
        $event->content = 'Hello';
        $event->body = '<b>Zachary send second email</b>';

        $this->trigger(self::SEND_MAIL, $event);
    }
}
